spring:
  environment: production
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:CONSULTADORDB
    username: sa
    password: password
    driver-class-name: org.h2.Driver
    initialization-mode: always
    platform: h2
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  config:
    activate:
      on-profile: prod